definitions:
  web.ErrorApiMessage:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /addUser:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/uint64'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorApiMessage'
      summary: Adds a user
  /designs/add:
    post:
      parameters:
      - description: id of current device
        in: formData
        name: id
        required: true
        type: string
      - description: 'time of connection: 2012-11-01T22:08:41+00:00'
        in: formData
        name: time
        required: true
        type: string
      - description: device connected to
        in: formData
        name: other
        required: true
        type: integer
      - description: power of the connection
        in: formData
        name: power
        required: true
        type: integer
      - description: rssi of the connection
        in: formData
        name: rssi
        required: true
        type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/uint64'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorApiMessage'
      summary: Adds a design
swagger: "2.0"
